<?php
return array (
	'zh_cn' =>array('name'=>'简体中文'    ,'dispname'=>'简体中文'   ,'trans'=>'zh'),
	'zh_tw' =>array('name'=>'繁体中文'    ,'dispname'=>'繁體中文'   ,'trans'=>'cht'),
	'en'    =>array('name'=>'英语'        ,'dispname'=>'English'    ,'trans'=>'en' ),
	'ko'    =>array('name'=>'韩语'        ,'dispname'=>'한국의'     ,'trans'=>'kor'),
	'ja'    =>array('name'=>'日语'        ,'dispname'=>'日本語'     ,'trans'=>'jp' ),
	'fr'    =>array('name'=>'法语'        ,'dispname'=>'Français'   ,'trans'=>'fra'),
	'de'    =>array('name'=>'德语'        ,'dispname'=>'Deutsch'    ,'trans'=>'de' ),
	'ru'    =>array('name'=>'俄语'        ,'dispname'=>'русский' ,'trans'=>'ru' ),
	'th'    =>array('name'=>'泰语'        ,'dispname'=>'ไทย'         ,'trans'=>'th' ),
	'ar'    =>array('name'=>'阿拉伯语'    ,'dispname'=>'العربية'      ,'trans'=>'ara'),
	'pl'    =>array('name'=>'波兰语'      ,'dispname'=>'polski'     ,'trans'=>'pl' ),
	'pt'    =>array('name'=>'葡萄牙语'    ,'dispname'=>'português'  ,'trans'=>'pt' ),
	'ro'    =>array('name'=>'罗马尼亚语'  ,'dispname'=>'românesc'   ,'trans'=>'rom'),
	'it'    =>array('name'=>'意大利语'    ,'dispname'=>'lingua italiana','trans'=>'it' ),
	'bg'    =>array('name'=>'保加利亚语'  ,'dispname'=>'български','trans'=>'bul'),
	'hu'    =>array('name'=>'匈牙利语'    ,'dispname'=>'magyar'     ,'trans'=>'hu' ),
	'da'    =>array('name'=>'丹麦语'      ,'dispname'=>'dansk'      ,'trans'=>'dan'),
	'cs'    =>array('name'=>'捷克语'      ,'dispname'=>'český'      ,'trans'=>'cs' ),
	'el'    =>array('name'=>'希腊语'      ,'dispname'=>'ελληνικά','trans'=>'el' ),
	'es'    =>array('name'=>'西班牙语'    ,'dispname'=>'español'    ,'trans'=>'spa'),
	'et'    =>array('name'=>'爱沙尼亚语'  ,'dispname'=>'eesti'      ,'trans'=>'est'),
	'fi'    =>array('name'=>'芬兰语'      ,'dispname'=>'suomalainen','trans'=>'fin'),
	'nl'    =>array('name'=>'荷兰语'      ,'dispname'=>'Nederlands' ,'trans'=>'nl' ),
	'sv'    =>array('name'=>'瑞典语'      ,'dispname'=>'svenska'    ,'trans'=>'swe'),
	'sl'    =>array('name'=>'斯洛文尼亚语','dispname'=>'slovenski' ,'trans'=>'slo'),
);